groups:
- name: api_instance
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'
    for: 10s
    # Annotation - additional informational labels to store more information
    annotations:
      summary: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 seconds.'