global:
  scrape_interval: 10s
rule_files:
  - "alert_rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          - microservicios-talleres-alertmanager-1:9093
scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: 
        - microservicios-talleres-app-1:3000
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090
  - job_name: 'grafana'
    static_configs:
      - targets:
          - microservicios-talleres-grafana-1:3000
  - job_name: 'loki'
    static_configs:
      - targets:
          - microservicios-talleres-loki-1:3100
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets:
          - mongodb-exporter:9216
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - microservicios-talleres-node-exporter-1:9100
  - job_name: 'jenkins-1'
    metrics_path: /prometheus
    static_configs:
      - targets:
          - microservicios-talleres-jenkins-1:8080
  - job_name: 'python'
    static_configs:
      - targets:
          - microservicios-talleres-python_service-1:5000